apiVersion: apps/v1
kind: Deployment
metadata:
  name: dojomaster
  labels:
    app: dojomaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dojomaster
  template:
    metadata:
      labels:
        app: dojomaster
    spec:
      containers:
        - name: dojomaster
          image: ghcr.io/bixson/dojomaster:latest
          ports:
            - containerPort: 7681
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
